# Generated by Django 2.0 on 2021-10-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=123456, max_length=20, unique=True)),
                ('password', models.CharField(default=123456, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'other')], default='m', max_length=1)),
                ('password', models.CharField(default=123456, max_length=20)),
                ('recommended', models.CharField(default='Self Join', max_length=255)),
                ('referer_code', models.CharField(max_length=255)),
            ],
        ),
    ]
